version: '3'

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - symnet
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    volumes:
      - mongodb-data:/data/db
    networks:
      - symnet
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.stats()", "--username=root", "--password=examplepassword"]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # RabbitMQ management interface
      - "5672:5672"    # RabbitMQ default
    networks:
      - symnet
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 3

  binance-app:
    image: yitech/symmetric_arbitrage:latest
    depends_on:
      - redis
      - mongodb
      - rabbitmq
    networks:
      - symnet
    volumes:
      - /Users/yite/Projects/sym_arbitrage/log:/app/log
      - /Users/yite/Projects/sym_arbitrage/config:/app/config
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    entrypoint:
      - dockerize
      - -wait
      - tcp://mongodb:27017
      - -wait
      - tcp://redis:6379
      - -wait
      - tcp://rabbitmq:5672
      - -timeout
      - 60s
    command: ["uvicorn", "exhost.binancefuture.rest_manager:app", "--host", "0.0.0.0", "--port", "8000"]

  binance-worker:
    image: yitech/symmetric_arbitrage:latest
    depends_on:
      - redis
      - mongodb
      - rabbitmq
    volumes:
      - /Users/yite/Projects/sym_arbitrage/log:/app/log
      - /Users/yite/Projects/sym_arbitrage/config:/app/config
    environment:
      - PYTHONPATH=/app
    entrypoint:
      - dockerize
      - -wait
      - tcp://mongodb:27017
      - -wait
      - tcp://redis:6379
      - -wait
      - tcp://rabbitmq:5672
      - -timeout
      - 60s
    command: ["python", "exhost/binancefuture/rest_worker.py"]
    networks:
      - symnet

  binance-ws:
    image: yitech/symmetric_arbitrage:latest
    depends_on:
      - redis
      - mongodb
      - rabbitmq
    volumes:
      - /Users/yite/Projects/sym_arbitrage/log:/app/log
      - /Users/yite/Projects/sym_arbitrage/config:/app/config
    environment:
      - PYTHONPATH=/app
    ports:
      - "8765:8765"
    entrypoint:
      - dockerize
      - -wait
      - tcp://mongodb:27017
      - -wait
      - tcp://redis:6379
      - -wait
      - tcp://rabbitmq:5672
      - -timeout
      - 60s
    command: [ "python", "exhost/binancefuture/ws_orderbook.py" ]
    networks:
      - symnet

networks:
  symnet:
    driver: bridge

volumes:
  mongodb-data:
